const data = [
    {
        "_id": "63a0813c73d6745f7d355daf",
        "name": "The Power of HABIT",
        "description": "The Power of HABIT: Why We Do What We Do in Life and Business. A young woman walks into a laboratory. Over the past two years, she has transformed almost every aspect of her life. She has quit smoking, run a marathon, and been promoted at work. The patterns inside her brain, neurologists discover, have fundamentally changed.",
        "price": 360,
        "author": "Charles Duhigg",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51ejXdSceNL._AA300_.jpg",
        "incart": false,
        "category": "business",
        "type": "book",
        "rating": 4
    },
    {
        "_id": "63a0813c73d6745f7d355db0",
        "name": "Think and Grow Rich",
        "description": "'Think and Grow Rich!' explains entrepreneur Andrew Carnegie’s secret to success, revealed to Napoleon Hill during private interviews with Carnegie, the richest man of his time, and during more than 20 years of research into the lives and philosophies of more than 500 of the most successful people in America. This timeless classic presents a systematic nuts-and-bolts approach to developing the skills and mindset required to achieve exceptional success in any field or endeavor, personal or professional. Hill explains in detail 13 steps required to achieve those goals. The book contains numerous self-tests and checklists.",
        "price": 280,
        "author": "Napoleon Hill",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51ZouHoBGtL._SX315_BO1,204,203,200_.jpg",
        "incart": true,
        "category": "business",
        "type": "book",
        "rating": 3.6
    },
    {
        "_id": "63a0813c73d6745f7d355db1",
        "name": "The 7 Habits of Highly Effective People",
        "description": "The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change. The 7 Habits of Highly Effective People, the beloved classic that has sold over 20 million copies worldwide, is celebrating its 25th anniversary with this reissue! With a new foreword, the wisdom of the 7 Habits still holds true after all these years. The 7 Habits have become so famous because they work. They have been integrated into everyday thinking by many millions of people. The reason: They work. Habit 1: Be Proactive. Habit 2: Begin with the End in Mind. Habit 3: Put First Things First. Habit 4: Think Win/Win. Habit 5: Seek First to Understand, Then to Be Understood. Habit 6: Synergize. Habit 7: Sharpen the Saw. The book presents a principle-centered approach for solving personal and professional problems.",
        "price": 150,
        "author": "Stephen R. Covey",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51Myx6jMujL._AA300_.jpg",
        "incart": true,
        "category": "business",
        "type": "book",
        "rating": 4.2
    },
    {
        "_id": "63a0813c73d6745f7d355db2",
        "name": "Principles: Life and Work",
        "description": "In Principles, Dalio shares what he's learned over the course of his remarkable career. He argues that life, management, economics, and investing can all be systemized into rules and understood like machines.",
        "price": 150,
        "author": "Ray Dalio",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51UyMOpP%2BGL._AA300_.jpg",
        "incart": false,
        "category": "business",
        "type": "book",
        "rating": 2
    },
    {
        "_id": "63a0813c73d6745f7d355db3",
        "name": "How to Win Friends & Influence People",
        "description": "For more than sixty years the rock-solid, time-tested advice in this book has carried thousands of now famous people up the ladder of success in their business and personal lives. Now this previously revised and updated bestseller is available in trade paperback for the first time to help you achieve your maximum potential throughout the next century!",
        "price": 260,
        "author": "Dale Carnegie",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51PWIy1rHUL._AA300_.jpg",
        "incart": true,
        "category": "business",
        "type": "book",
        "rating": 3
    },
    {
        "_id": "63a0813c73d6745f7d355db4",
        "name": "The Whole 30",
        "description": "Since 2009, Melissa Hartwig’s critically-acclaimed Whole30 program has quietly led hundreds of thousands of people to effortless weight loss and better health—along with stunning improvements in sleep quality, energy levels, mood, and self-esteem. The program accomplishes all of this by specifically targeting people’s habits and emotional relationships with food. The Whole30 is designed to help break unhealthy patterns of behavior, stop stress-related comfort eating, and reduce cravings, particularly for sugar and carbohydrates. Many Whole30 participants have described achieving 'food freedom'—in just thirty days.",
        "price": 130,
        "author": "Melissa Hartwig",
        "image": "https://images-na.ssl-images-amazon.com/images/I/61WFjEDBktL._SX437_BO1,204,203,200_.jpg",
        "incart": true,
        "category": "cookbooks",
        "type": "book",
        "rating": 5
    },
    {
        "_id": "63a0813c73d6745f7d355db5",
        "name": "The Food Lab",
        "description": "Ever wondered how to pan-fry a steak with a charred crust and an interior that's perfectly medium-rare from edge to edge when you cut into it? How to make homemade mac 'n' cheese that is as satisfyingly gooey and velvety-smooth as the blue box stuff, but far tastier? How to roast a succulent, moist turkey (forget about brining!)―and use a foolproof method that works every time?",
        "price": 160,
        "author": "J. Kenji López-Alt",
        "image": "https://images-na.ssl-images-amazon.com/images/I/419aGgQt-5L._SX392_BO1,204,203,200_.jpg",
        "incart": true,
        "category": "cookbooks",
        "type": "book",
        "rating": 3
    },
    {
        "_id": "63a0813c73d6745f7d355db6",
        "name": "True Fiction (Ian Ludlow Thrillers)",
        "description": "A breakneck thriller where truth and fiction collide for the unluckiest writer alive.",
        "price": 299,
        "author": "Lee Goldberg",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51UbplnqSgL._SX331_BO1,204,203,200_.jpg",
        "incart": false,
        "category": "mystery",
        "type": "book",
        "rating": 4
    },
    {
        "_id": "63a0813c73d6745f7d355db7",
        "name": "The Last Move",
        "description": "An FBI agent must catch a copycat killer. The only difference this time: she's the final victim.",
        "price": 149,
        "author": "Mary Burton",
        "image": "https://images-na.ssl-images-amazon.com/images/I/514jRDA21TL._AA300_.jpg",
        "incart": true,
        "category": "mystery",
        "type": "book",
        "rating": 2
    },
    {
        "_id": "63a0813c73d6745f7d355db8",
        "name": "Stillhouse Lake (Stillhouse Lake Series)",
        "description": "Gina Royal is the definition of average—a shy Midwestern housewife with a happy marriage and two adorable children. But when a car accident reveals her husband’s secret life as a serial killer, she must remake herself as Gwen Proctor—the ultimate warrior mom.",
        "price": 165,
        "author": "Rachel Caine",
        "image": "https://images-na.ssl-images-amazon.com/images/I/41RTt7alEqL._SX332_BO1,204,203,200_.jpg",
        "incart": true,
        "category": "mystery",
        "type": "book",
        "rating": 1
    },
    {
        "_id": "63a0813c73d6745f7d355db9",
        "name": "Harry Potter and the Sorcerer's Stone",
        "description": "On Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
        "price": 265,
        "author": "J.K.Rowling",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51qlgJ6ZojL.jpg",
        "incart": true,
        "category": "scifi",
        "type": "book",
        "rating": 3
    },
    {
        "_id": "63a0813c73d6745f7d355dba",
        "name": "A Game of Thrones: A Song of Ice and Fire, Book 1",
        "description": "As a whole, this series comprises a genuine masterpiece of modern fantasy, bringing together the best the genre has to offer. Magic, mystery, intrigue, romance, and adventure fill these pages and transport us to a world unlike any we have ever experienced.",
        "price": 250,
        "author": "George R. R. Martin",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51n5SAiAz7L._AA300_.jpg",
        "incart": false,
        "category": "accessories",
        "type": "book",
        "rating": 2
    },
    {
        "_id": "63a0813c73d6745f7d355dbb",
        "name": "The Lord of the Rings: One Volume",
        "description": "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others.",
        "price": 220,
        "author": "J.R.R. Tolkien",
        "image": "https://images-na.ssl-images-amazon.com/images/I/51d4G0sFMzL.jpg",
        "incart": true,
        "category": "scifi",
        "type": "book",
        "rating": 4
    },
    {
        "_id": "63a0813c73d6745f7d355dbc",
        "name": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        "price": 399,
        "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
        "category": "men",
        "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        "rating": 3.9,
        "type": "acessories"
    },
    {
        "_id": "63a0813c73d6745f7d355dbd",
        "name": "Mens Casual Premium Slim Fit T-Shirts ",
        "price": 799,
        "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
        "rating": 4.1,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dbe",
        "name": "Mens Cotton Jacket",
        "price": 699,
        "description": "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
        "rating": 4.7,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dbf",
        "name": "Mens Casual Slim Fit",
        "price": 499,
        "description": "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
        "category": "men",
        "image": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
        "rating": 2.1,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dc0",
        "name": "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
        "price": 40695,
        "description": "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
        "category": "jewelery",
        "image": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
        "rating": 4.6,
        "type": "jewelry"
    },
    {
        "_id": "63a0813c73d6745f7d355dc1",
        "name": "Solid Gold Petite Micropave ",
        "price": 1299,
        "description": "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
        "category": "jewelery",
        "image": "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
        "rating": 3.9,
        "type": "jewelry"
    },
    {
        "_id": "63a0813c73d6745f7d355dc2",
        "name": "White Gold Plated Princess",
        "price": 999,
        "description": "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
        "category": "jewelery",
        "image": "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
        "rating": 3,
        "type": "jewelry"
    },
    {
        "_id": "63a0813c73d6745f7d355dc3",
        "name": "Pierced Owl Rose Gold Plated Stainless Steel Double",
        "price": 1099,
        "description": "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
        "category": "jewelery",
        "image": "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
        "rating": 1.9,
        "type": "jewelry"
    },
    {
        "_id": "63a0813c73d6745f7d355dc4",
        "name": "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
        "price": 1640,
        "description": "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
        "category": "hdd",
        "image": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
        "rating": 3.3,
        "type": "electronics"
    },
    {
        "_id": "63a0813c73d6745f7d355dc5",
        "name": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
        "price": 459,
        "description": "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
        "category": "ssd",
        "image": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
        "rating": 2.9,
        "type": "electronics"
    },
    {
        "_id": "63a0813c73d6745f7d355dc6",
        "name": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
        "price": 1199,
        "description": "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
        "category": "ssd",
        "image": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
        "rating": 4.8,
        "type": "electronics"
    },
    {
        "_id": "63a0813c73d6745f7d355dc7",
        "name": "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
        "price": 2149,
        "description": "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
        "category": "hdd",
        "image": "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
        "rating": 4.8,
        "type": "electronics"
    },
    {
        "_id": "63a0813c73d6745f7d355dc8",
        "name": "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
        "price": 8599,
        "description": "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
        "category": "monitor",
        "image": "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
        "rating": 2.9,
        "type": "electronics"
    },
    {
        "_id": "63a0813c73d6745f7d355dc9",
        "name": "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
        "price": 9999,
        "description": "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
        "category": "monitor",
        "image": "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
        "rating": 2.2,
        "type": "electronics"
    },
    {
        "_id": "63a0813c73d6745f7d355dca",
        "name": "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
        "price": 569,
        "description": "The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
        "category": "women",
        "image": "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
        "rating": 2.6,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dcb",
        "name": "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
        "price": 1499,
        "description": "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
        "category": "women",
        "image": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
        "rating": 2.9,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dcc",
        "name": "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        "price": 1099,
        "description": "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
        "category": "women",
        "image": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
        "rating": 3.8,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dcd",
        "name": "MBJ Women's Solid Short Sleeve Boat Neck V ",
        "price": 989,
        "description": "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
        "category": "women",
        "image": "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
        "rating": 4.7,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dce",
        "name": "Opna Women's Short Sleeve Moisture",
        "price": 795,
        "description": "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
        "category": "women",
        "image": "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
        "rating": 4.5,
        "type": "cloths"
    },
    {
        "_id": "63a0813c73d6745f7d355dcf",
        "name": "DANVOUY Womens T Shirt Casual Cotton Short",
        "price": 699,
        "description": "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
        "category": "women",
        "image": "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
        "rating": 3.6,
        "type": "cloths"
    },
    {
        "_id": "63db932fb98230e4eaec8947",
        "name": "Nike React Infinity Run Flyknit",
        "brand": "nike",
        "gender": "men",
        "category": "running",
        "price": 16000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zX42Nc.jpg",
        "slug": "nike-react-infinity-run-flyknit",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "The Nike React Infinity Run Flyknit is a premium running shoe designed to provide unparalleled comfort, support, and performance. The shoe features Nike's innovative React foam technology, which delivers a responsive and cushioned ride, perfect for long-distance runs and high-intensity training sessions."
    },
    {
        "_id": "63db932fb98230e4eaec894a",
        "name": "Nike Joyride Run Flyknit",
        "brand": "nike",
        "gender": "women",
        "category": "running",
        "price": 18000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/99a7d3cb-e40c-4474-91c2-0f2e6d231fd2/joyride-run-flyknit-womens-running-shoe-HcfnJd.jpg",
        "slug": "nike-joyride-run-flyknit",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The Nike Joyride Run Flyknit is a high-performance running shoe that is designed to provide an unparalleled level of comfort and support. It features Nike's innovative Joyride technology, which consists of thousands of tiny beads that are strategically placed within the sole of the shoe."
    },
    {
        "_id": "63db932fb98230e4eaec8959",
        "name": "SS-MS-0075",
        "brand": "hushpuppies",
        "gender": "women",
        "category": "casual",
        "price": 2500,
        "is_in_inventory": true,
        "items_left": 7,
        "image": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009170000-479-SS-MS-0075-Red_800x800.jpg?v=1570688687",
        "slug": "ss-ms-0075",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "TheThe Hush Puppies SS-MS-0075 is a stylish and comfortable shoe that is perfect for everyday wear. Made with high-quality leather, the shoe features a classic design with a modern twist. The shoe is designed to provide all-day comfort with its cushioned footbed and flexible outsole. With its versatile style, the Hush Puppies SS-MS-0075 can easily be dressed up or down to suit any occasion."
    },
    {
        "_id": "63db932fb98230e4eaec894e",
        "name": "Nike Mercurial Vapor 13 Elite Tech Craft FG",
        "brand": "nike",
        "gender": "men",
        "category": "football",
        "price": 14500,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/vhbwnkor8sxt8qtecgia/mercurial-vapor-13-elite-tech-craft-fg-firm-ground-soccer-cleat-l38JPj.jpg",
        "slug": "nike-mercurial-vapor-13-elite-tech-craft-fg",
        "featured": 0,
        "type": "shoe",
        "rating": 5,
        "description": "The Nike Mercurial Vapor 13 Elite Tech Craft FG is a premium soccer cleat designed for elite-level performance. The upper is made of a high-quality leather material, which provides a soft touch and a comfortable fit while maintaining durability."
    },
    {
        "_id": "63db932fb98230e4eaec8950",
        "name": "Nike Air Force 1",
        "brand": "nike",
        "gender": "kids",
        "category": "casual",
        "price": 9000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/178b2a46-3ee4-492b-882e-f71efdd53a36/air-force-1-big-kids-shoe-2zqp8D.jpg",
        "slug": "nike-air-force-1",
        "featured": 0,
        "type": "shoe",
        "rating": 2,
        "description": "The Nike Air Force 1 is a classic and iconic sneaker that has been popular since its debut in 1982. The shoe features a clean and simple design, with a low-cut silhouette and a durable leather upper.The Nike Air Force 1 also features Nike's Air cushioning technology in the sole, which provides excellent comfort and support for all-day wear. The shoe is available in a wide range of colors and styles, making it a versatile option for any outfit or occasion."
    },
    {
        "_id": "63db932fb98230e4eaec8955",
        "name": "Austin",
        "brand": "hushpuppies",
        "gender": "men",
        "category": "formal",
        "price": 7500,
        "is_in_inventory": true,
        "items_left": 2,
        "image": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/Austin-Coffee_800x800.jpg?v=1574772988",
        "slug": "austin",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "The NiThe Hush Puppies Austin is a stylish and comfortable shoe that is perfect for everyday wear. Made with high-quality leather, the shoe features a classic design with a modern twist. The shoe is designed to provide all-day comfort with its cushioned footbed and flexible outsole. With its versatile style, the Hush Puppies Austin can easily be dressed up or down to suit any occasion."
    },
    {
        "_id": "63db932fb98230e4eaec895e",
        "name": "NMD_R1",
        "brand": "adidas",
        "gender": "kids",
        "category": "running",
        "price": 12000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/99ca762cb9054caf82fbabc500fd146e_9366/NMD_R1_Shoes_Blue_FY9392_01_standard.jpg",
        "slug": "nmd_r1",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The shoe features Adidas' innovative Boost technology, which provides responsive cushioning and energy return for a comfortable and efficient stride.The NMD_R1 also features a breathable mesh upper, with welded overlays and a unique midsole design that provides stability and support. The shoe's distinctive style is a fusion of modern design and retro-inspired elements, making it a versatile choice for a wide range of outfits and occasions."
    },
    {
        "_id": "63db932fb98230e4eaec8951",
        "name": "Nike Air Max 90",
        "brand": "nike",
        "gender": "kids",
        "category": "casual",
        "price": 10000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/8439f823-86cf-4086-81d2-4f9ff9a66866/air-max-90-big-kids-shoe-1wzwJM.jpg",
        "slug": "nike-air-max-90",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "The Nike Air Max 90 features a retro-inspired design with visible Air cushioning in the heel, providing comfort and support for everyday wear.The upper of the shoe is made of durable leather and breathable mesh, with overlays for added structure and support. The Nike Air Max 90 is available in a wide range of colors and styles, making it a versatile option for any outfit."
    },
    {
        "_id": "63db932fb98230e4eaec8958",
        "name": "SS-HL-0128",
        "brand": "hushpuppies",
        "gender": "women",
        "category": "formal",
        "price": 3500,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/000300242-484-SS-HL-0128-Blue_800x800.jpg?v=1583235174",
        "slug": "ss-hl-0128",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "The Hush Puppies SS-HL-0128 is a stylish and comfortable shoe that is perfect for everyday wear. Made with high-quality leather, the shoe features a classic design with a modern twist. The shoe is designed to provide all-day comfort with its cushioned footbed and flexible outsole. With its versatile style, the Hush Puppies SS-HL-0128 can easily be dressed up or down to suit any occasion."
    },
    {
        "_id": "63db932fb98230e4eaec895c",
        "name": "X_PLR",
        "brand": "adidas",
        "gender": "kids",
        "category": "casual",
        "price": 6500,
        "is_in_inventory": true,
        "items_left": 5,
        "image": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/a36518227134495da766ab9d01772fa2_9366/X_PLR_Shoes_Red_FY9063_01_standard.jpg",
        "slug": "x_plr",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The X_PLR is a popular sneaker model from Adidas, designed for everyday wear and athletic performance. The shoe features a minimalist design with a sleek and modern look.The upper of the X_PLR is made of breathable mesh and synthetic overlays, providing both ventilation and support. The shoe also features a cushioned midsole and a rubber outsole for traction and durability."
    },
    {
        "_id": "63db932fb98230e4eaec8962",
        "name": "SK80-Low",
        "brand": "vans",
        "gender": "men",
        "category": "casual",
        "price": 6000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://images.vans.com/is/image/Vans/UUK24I-HERO?$583x583$",
        "slug": "sk80-low",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "Vans is known for creating comfortable and stylish shoes, so any of their current models will have similar features such as a durable canvas or leather upper and a rubber outsole with excellent traction."
    },
    {
        "_id": "63db932fb98230e4eaec8963",
        "name": "Michael Feburary SK8-Hi",
        "brand": "vans",
        "gender": "men",
        "category": "casual",
        "price": 7200,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://images.vans.com/is/image/Vans/MV122M-HERO?$583x583$",
        "slug": "michael-feburary-sk8-hi",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "The Michael February SK8-Hi is a limited edition sneaker collaboration between Vans and South African surfer Michael February.A woven upper that mimics traditional surfboard craftsmanship.The Michael February SK8-Hi also features the classic Vans high-top silhouette with a padded collar for support and flexibility, a vulcanized rubber outsole for traction, and the Vans signature Waffle tread pattern. With its distinctive design and high-quality construction, the Michael February SK8-Hi is a standout sneaker that combines fashion and function."
    },
    {
        "_id": "63db932fb98230e4eaec8953",
        "name": "Nike Joyride Dual Run",
        "brand": "nike",
        "gender": "kids",
        "category": "running",
        "price": 11000,
        "is_in_inventory": false,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/33888130-0320-41a1-ba53-a026decd8aa2/joyride-dual-run-big-kids-running-shoe-1HDJF8.jpg",
        "slug": "nike-joyride-dual-run",
        "featured": 0,
        "type": "shoe",
        "rating": 5,
        "description": "The Nike Joyride Dual Run is a running shoe designed for maximum comfort and support. It features a unique cushioning system that consists of thousands of tiny beads in the midsole, which mold to the shape of your foot and provide a personalized fit.The upper of the shoe is made of breathable mesh and lightweight synthetic materials, providing both ventilation and support. "
    },
    {
        "_id": "63db932fb98230e4eaec894c",
        "name": "Nike Phantom Vision Elite Dynamic Fit FG",
        "brand": "nike",
        "gender": "women",
        "category": "football",
        "price": 15000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/s1amp7uosrn0nqpsxeue/phantom-vision-elite-dynamic-fit-fg-firm-ground-soccer-cleat-19Kv1V.jpg",
        "slug": "nike-phantom-vision-elite-dynamic-fit-fg",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "The Nike Phantom Vision Elite Dynamic Fit FG is a high-performance soccer cleat designed for precision and control on the field. The upper of the shoe features a Flyknit construction, providing a snug and comfortable fit, while the Quadfit mesh inner bootie adapts to the shape of your foot for a custom feel.The Phantom Vision Elite also features a Ghost Lace system that provides a clean strike zone and a secure fit. "
    },
    {
        "_id": "63db932fb98230e4eaec8949",
        "name": "Nike Air Zoom Pegasus 37",
        "brand": "nike",
        "gender": "women",
        "category": "running",
        "price": 12000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-33b0a0a5-c171-46cc-ad20-04a768703e47/air-zoom-pegasus-37-womens-running-shoe-Jl0bDf.jpg",
        "slug": "nike-air-zoom-pegasus-37",
        "featured": 0,
        "type": "shoe",
        "rating": 5,
        "description": "The Nike Air Zoom Pegasus 37 is a popular and versatile running shoe designed for both casual runners and serious athletes. The shoe features a breathable mesh upper that is lightweight and durable, with a full-length Air Zoom unit in the midsole that provides responsive cushioning and support.The Pegasus 37 also features a unique React foam in the forefoot that provides a springy and comfortable feel with every step. The shoe's outsole is made of durable rubber with a unique waffle pattern that provides excellent traction on both wet and dry surfaces."
    },
    {
        "_id": "63db932fb98230e4eaec894b",
        "name": "Nike Mercurial Vapor 13 Elite FG",
        "brand": "nike",
        "gender": "women",
        "category": "football",
        "price": 25000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9dda6202-e2ff-4711-9a09-0fcb7d90c164/mercurial-vapor-13-elite-fg-firm-ground-soccer-cleat-14MsF2.jpg",
        "slug": "nike-mercurial-vapor-13-elite-fg",
        "featured": 0,
        "type": "shoe",
        "rating": 5,
        "description": "The Nike Mercurial Vapor 13 Elite FG is a high-performance soccer cleat designed for speed and agility on the field. The upper of the shoe is made of a lightweight and durable material with Nike's Flyknit technology, which provides a comfortable and secure fit that moves with your foot.The Mercurial Vapor 13 Elite also features a new plate design with a split sole that provides excellent traction and support, while reducing the weight of the shoe."
    },
    {
        "_id": "63db932fb98230e4eaec895f",
        "name": "NMD_R1 Flash Red",
        "brand": "adidas",
        "gender": "women",
        "category": "casual",
        "price": 14000,
        "is_in_inventory": true,
        "items_left": 5,
        "image": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/90f85768e3894aeaab67aba0014a3379_9366/NMD_R1_Shoes_Red_FY9389_01_standard.jpg",
        "slug": "nmd_r1-flash-red",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The NMD_R1 Flash Red is a stylish and comfortable sneaker from Adidas. The shoe features a breathable and flexible Primeknit upper with a sock-like fit, which molds to the shape of your foot for a comfortable and secure feel.The NMD_R1 Flash Red also features Adidas' signature Boost cushioning technology, providing a responsive and comfortable feel with every step.The shoe's outsole is made of durable rubber with a unique tread pattern that provides excellent traction on a variety of surfaces."
    },
    {
        "_id": "63db932fb98230e4eaec8956",
        "name": "SS-HL-0135",
        "brand": "hushpuppies",
        "gender": "women",
        "category": "formal",
        "price": 3000,
        "is_in_inventory": true,
        "items_left": 6,
        "image": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009240000-11-SS-HL-0135-Black_800x800.jpg?v=1572264270",
        "slug": "ss-hl-0135",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The Hush Puppies SS-HL-0135 is a stylish and comfortable shoe that is perfect for everyday wear. Made with high-quality leather, the shoe features a classic design with a modern twist. The shoe is designed to provide all-day comfort with its cushioned footbed and flexible outsole. With its versatile style, the Hush Puppies SS-HL-0135 can easily be dressed up or down to suit any occasion."
    },
    {
        "_id": "63db932fb98230e4eaec895a",
        "name": "SS-PM-0093",
        "brand": "hushpuppies",
        "gender": "women",
        "category": "casual",
        "price": 3000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/SS-PM-0093_1_800x800.jpg?v=1570601253",
        "slug": "ss-pm-0093",
        "featured": 0,
        "type": "shoe",
        "rating": 2,
        "description": "The Hush Puppies SS-PM-0093 is a stylish and comfortable shoe that is perfect for everyday wear. Made with high-quality leather, the shoe features a classic design with a modern twist. The shoe is designed to provide all-day comfort with its cushioned footbed and flexible outsole. With its versatile style, the Hush Puppies SS-PM-0093 can easily be dressed up or down to suit any occasion."
    },
    {
        "_id": "63db932fb98230e4eaec895d",
        "name": "Stan Smith",
        "brand": "adidas",
        "gender": "kids",
        "category": "casual",
        "price": 5500,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/d0720712d81e42b1b30fa80800826447_9366/Stan_Smith_Shoes_White_M20607_M20607_01_standard.jpg",
        "slug": "stan-smith",
        "featured": 0,
        "type": "shoe",
        "rating": 5,
        "description": "The Stan Smith's upper is made of premium leather with a soft and smooth feel, while the rubber sole provides traction and durability. The shoe's simple design makes it a versatile choice for both casual and sporty outfits.In addition to its timeless design, the Stan Smith has been worn by many celebrities and athletes, making it a cultural icon in the world of sneakers. It is available in a range of colors and styles to suit any preference or outfit."
    },
    {
        "_id": "63db932fb98230e4eaec894d",
        "name": "Nike Phantom Venom Academy FG",
        "brand": "nike",
        "gender": "women",
        "category": "football",
        "price": 8000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/whegph8z9ornhxklc8rp/phantom-venom-academy-fg-firm-ground-soccer-cleat-6JVNll.jpg",
        "slug": "nike-phantom-venom-academy-fg",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The Nike Phantom Venom Academy FG is a high-performance soccer cleat designed for precision and power on the field. The shoe features a textured synthetic upper that provides enhanced control and touch when dribbling and passing.The Phantom Venom Academy FG also features a plate design with a combination of chevron and hexagonal studs, which provide excellent traction and stability on firm-ground surfaces.The outsole of the shoe is made of durable and flexible material that allows for quick movements and sharp turns."
    },
    {
        "_id": "63db932fb98230e4eaec894f",
        "name": "Nike Mercurial Superfly 7 Pro MDS FG",
        "brand": "nike",
        "gender": "men",
        "category": "football",
        "price": 13700,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-a52a8aec-22dc-4982-961b-75c5f4c72805/mercurial-superfly-7-pro-mds-fg-firm-ground-soccer-cleat-mhcpdN.jpg",
        "slug": "nike-mercurial-superfly-7-pro-mds-fg",
        "featured": 0,
        "type": "shoe",
        "rating": 3,
        "description": "The Nike Mercurial Superfly 7 Pro MDS FG is a high-performance soccer cleat designed for speed and agility on the field. The shoe features a Flyknit upper that provides a comfortable and secure fit, while the All Conditions Control (ACC) technology allows for improved ball control in any weather conditions.The Mercurial Superfly 7 Pro MDS FG also features a plate design with a combination of chevron and angular studs, which provide excellent traction and stability on firm-ground surfaces. The outsole of the shoe is made of durable and flexible material that allows for quick movements and sharp turns."
    },
    {
        "_id": "63db932fb98230e4eaec8952",
        "name": "Nike Air Max 90 LTR",
        "brand": "nike",
        "gender": "kids",
        "category": "casual",
        "price": 11000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-620aeb37-1b28-44b0-9b14-5572f8cbc948/air-max-90-ltr-big-kids-shoe-hdNLQ5.jpg",
        "slug": "nike-air-max-90-ltr",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The Nike Air Max 90 LTR is a classic sneaker that has been updated with modern materials and design. The shoe features a leather upper with overlays for durability and support, while the iconic Air Max unit in the heel provides cushioning and comfort.The Air Max 90 LTR also features a rubber outsole with a Waffle pattern for traction and durability, making it a reliable choice for everyday wear. The shoe's design is both stylish and functional, with a range of colorways to suit any outfit or personal style."
    },
    {
        "_id": "63db932fb98230e4eaec8954",
        "name": "Nike Renew Run",
        "brand": "nike",
        "gender": "kids",
        "category": "running",
        "price": 8000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-73e54c0b-11a6-478b-9f90-bd97fcde872d/renew-run-big-kids-running-shoe-5Bpz93.jpg",
        "slug": "nike-renew-run",
        "featured": 0,
        "type": "shoe",
        "rating": 2,
        "description": "The Nike Renew Run is a versatile and comfortable running shoe designed for daily training and casual wear. The shoe features a lightweight and breathable mesh upper that provides a comfortable and secure fit, while the Nike Renew foam sole delivers a soft and responsive feel.\nThe Renew Run also features a durable rubber outsole with a waffle pattern for traction and durability, making it a reliable choice for running on a variety of surfaces. The shoe's design is both stylish and functional, with a range of colorways to suit any outfit or personal style."
    },
    {
        "_id": "63db932fb98230e4eaec8948",
        "name": "Nike React Miler",
        "brand": "nike",
        "gender": "men",
        "category": "running",
        "price": 13000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5cc7de3b-2afc-49c2-a1e4-0508997d09e6/react-miler-mens-running-shoe-DgF6nr.jpg",
        "slug": "nike-react-miler",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The Nike React Miler is a reliable and durable running shoe designed for daily training and long-distance running. The shoe features a breathable mesh upper that provides a comfortable and secure fit, while the Nike React foam sole delivers a soft and responsive feel with each stride.The React Miler also features a durable rubber outsole with a waffle pattern for traction and durability, making it a reliable choice for running on a variety of surfaces. The shoe's design is both stylish and functional, with a range of colorways to suit any outfit or personal style."
    },
    {
        "_id": "63db932fb98230e4eaec8957",
        "name": "SS-HL-0136",
        "brand": "hushpuppies",
        "gender": "women",
        "category": "formal",
        "price": 5000,
        "is_in_inventory": true,
        "items_left": 4,
        "image": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009250000-779-SS-HL-0136-Coffee_800x800.jpg?v=1571900372",
        "slug": "ss-hl-0136",
        "featured": 0,
        "type": "shoe",
        "rating": 5,
        "description": "The Hush Puppies SS-HL-0136 is a stylish and comfortable shoe that is perfect for everyday wear. Made with high-quality leather, the shoe features a classic design with a modern twist. The shoe is designed to provide all-day comfort with its cushioned footbed and flexible outsole. With its versatile style, the Hush Puppies SS-HL-0136 can easily be dressed up or down to suit any occasion."
    },
    {
        "_id": "63db932fb98230e4eaec895b",
        "name": "Nizza X Disney",
        "brand": "adidas",
        "gender": "kids",
        "category": "casual",
        "price": 5500,
        "is_in_inventory": true,
        "items_left": 6,
        "image": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/ef901c7aeac042578eceab9d0159196c_9366/Nizza_x_Disney_Sport_Goofy_Shoes_White_FW0651_01_standard.jpg",
        "slug": "nizza-x-disney",
        "featured": 0,
        "type": "shoe",
        "rating": 1,
        "description": "The Nizza X Disney is a collaboration between Adidas Originals and Disney that reimagines the classic Nizza sneaker with playful Disney-inspired design elements. The shoe features a canvas upper with a classic low-top silhouette, and is available in a range of colorways inspired by beloved Disney characters like Mickey Mouse and Minnie Mouse.The Nizza X Disney also features unique design details, such as oversized embroidered patches on the heel and tongue that depict iconic Disney characters and logos. The shoe's design is both fun and nostalgic, making it a great choice for sneaker enthusiasts and Disney fans alike."
    },
    {
        "_id": "63db932fb98230e4eaec8960",
        "name": "Superstar",
        "brand": "adidas",
        "gender": "women",
        "category": "casual",
        "price": 9000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/12365dbc7c424288b7cdab4900dc7099_9366/Superstar_Shoes_White_FW3553_FW3553_01_standard.jpg",
        "slug": "superstar",
        "featured": 0,
        "type": "shoe",
        "rating": 5,
        "description": "The Superstar is a classic sneaker design by Adidas that has been a popular style since its debut in 1969. The shoe features a low-top silhouette with a leather upper and the signature three stripes on the sides.The Superstar also features a rubber shell toe cap, which adds durability and protection to the shoe. The outsole is made of durable rubber and features a herringbone pattern for traction and grip.Over the years, the Superstar has been updated with a range of colorways and materials, but the classic design remains a staple in the Adidas lineup. The shoe has also been worn by various celebrities, musicians, and athletes, cementing its place in sneaker culture."
    },
    {
        "_id": "63db932fb98230e4eaec8961",
        "name": "Club C Revenge Mens",
        "brand": "reebok",
        "gender": "men",
        "category": "casual",
        "price": 7000,
        "is_in_inventory": true,
        "items_left": 3,
        "image": "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/7599294868804d78a1b1ab6f01718a5e_9366/Club_C_Revenge_Men's_Shoes_White_FV9877_01_standard.jpg",
        "slug": "club-c-revenge-mens",
        "featured": 0,
        "type": "shoe",
        "rating": 4,
        "description": "The Club C Revenge Mens is a classic sneaker design by Reebok that blends retro style with modern comfort. The shoe features a clean, minimalist design with a leather upper and the signature Reebok logo on the side.\n\nThe Club C Revenge Mens also features a durable rubber outsole with a herringbone pattern for traction and grip, making it a reliable choice for everyday wear. The shoe's cushioned insole provides a comfortable fit, while the low-cut design allows for freedom of movement and a sleek, streamlined look."
    }
]